services:

  postgres:
    image: postgres:17-alpine
    container_name: sigpac-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sigpac-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./backend/cultura-api
      dockerfile: Dockerfile
    container_name: sigpac-migrations
    restart: "no"

    env_file:
      - .env.docker

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy

    command:
      [
        "./node_modules/.bin/typeorm",
        "migration:run",
        "-d",
        "dist/database/data-source.js"
      ]

    networks:
      - sigpac-network

  backend:
    build:
      context: ./backend/cultura-api
      dockerfile: Dockerfile

    container_name: sigpac-backend
    restart: unless-stopped

    env_file:
      - .env.docker

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully