export enum TipoMonumento {
  ESTATUA = 'ESTATUA',
  BUSTO = 'BUSTO',
  ESCULTURA = 'ESCULTURA',
  OBELISCO = 'OBELISCO',
  MONOLITO = 'MONOLITO',
  PLACA = 'PLACA',
  MEMORIAL = 'MEMORIAL',
  FUENTE = 'FUENTE',
  OTRO = 'OTRO',
}
